SportsStore/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using System.ComponentModel.DataAnnotations;


namespace SportsStore.Models
{
    public class Order
    {
        [HttpBindNever]
        public int Id { get; set; }
        [Required]
        public string Customer { get; set; }
        [Required]
        [HttpBindNever]
        public decimal TotalCost { get; set; }
        public ICollection<OrderLine> Lines { get; set; }
    }

    public class OrderLine
    {
        [HttpBindNever]
        public int Id { get; set; }
        [Required]
        [Range(0,100)]
        public int Count { get; set; }

        [Required]
        public int ProductId { get; set; }
        [HttpBindNever]
        public int OrderId { get; set; }

        [HttpBindNever]
        public Product Product { get; set; }
        [HttpBindNever]
        public Order Order { get; set; }
    }
}

SportsStore/Controllers/OrdersController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace SportsStore.Controllers
{
    public class OrdersController : ApiController
    {
        private IRepository Repository;
        public OrdersController()
        {
            Repository = (IRepository)GlobalConfiguration.Configuration.DependencyResolver.GetService(typeof(IRepository));
        }

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public IEnumerable<Order> List(Order order)
        {
            return Repository.Orders;
        }

        [HttpPost]
        public async Task<IHttpActionResult> CreateOrder(Order order)
        {
            if (ModelState.IsValid)
            {
                IDictionary<int, Product> products
                = Repository
                    .Products
                    .Where(
                            p => order
                                  .Lines
                                  .Select(ol => ol.OrderId)
                                  .Any(id => id == p.Id)
                            )
                            .ToDictionary(p=>p.Id);
                order.TotalCost = order
                                    .Lines
                                    .Sum(ol=>ol.Count*products[ol.ProductId].Price);

                await Repository.SaveOrderAsync(order);
                return Ok();
              }
            else
                return BadRequest(ModelState);
        }

        [HttpDelete]
        [Authorize(Roles = "Administrators")]
        public async Task DeleteOrder(int id)
        {
            await Repository.DeleteOrderAsync(id);
        }
    }
}

SportsStore/Controllers/PrepController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.Owin.Security;
using SportsStore.Infrastructure.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace SportsStore.Controllers
{
    public class PrepController : Controller
    {
        IRepository repository;
        public PrepController()
        {
            repository = new ProductRepository();
        }
        // GET: Prep
        public ActionResult Index()
        {
            return View(repository.Products);
        }
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> DeleteProduct(int id)
        {
            await repository.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> SaveProduct(Product product)
        {
            await repository.SaveProductAsync(product);
            return RedirectToAction("Index");
        }

        public ActionResult Orders()
        {
            return View(repository.Orders);
        }

        public async Task<ActionResult> DeleteOrder(int order)
        {
            await repository.DeleteOrderAsync(order);
            return RedirectToAction("Oders");
        }

        public async Task<ActionResult> SaveOrder(Order order)
        {
            await repository.SaveOrderAsync(order);
            return RedirectToAction("Orders");
        }
        public async Task<ActionResult> SingIn() {
            IAuthenticationManager authMgr = HttpContext.GetOwinContext().Authentication;
            StoreUserManager userMgr =
                HttpContext.GetOwinContext().GetUserManager<StoreUserManager>();

            StoreUser user = await userMgr.FindAsync("Admin","secret");
            authMgr.SignIn(await userMgr.CreateIdentityAsync(user,
                DefaultAuthenticationTypes.ApplicationCookie));
            return RedirectToAction("Index");
        }

        public ActionResult SingOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index");
        }
  }
}

SportsStore/Views/Prep/Index.cshtml
@model IEnumerable<SportsStore.Models.Product>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-primary">
    @Html.ActionLink("Sign In","singin","prep",null,new {@class="btn btn-primary" })
    @Html.ActionLink("Sign Out", "singout", "prep", null, new { @class = "btn btn-primary" })
    User: @(HttpContext.Current.User.Identity.Name)
</div>
<div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <table class="table table-striped">
        <tr><th>ID</th><th>Name</th><th>Category</th><th>Price</th></tr>
        @foreach (var p in Model)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.Category</td>
                <td>@p.Price</td>
            </tr>
        }
    </table>
</div>

@using (Html.BeginForm("SaveProduct", "Prep"))
{
    <input type="hidden" name="Name" value="Zippy Running Shoes" />
    <input type="hidden" name="Category" value="Running" />
    <input type="hidden" name="Description" value="Set a new Record Time" />
    <input type="hidden" name="Price" value="159.99" />

    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteproduct/2" class="btn btn-primary">Delete</a>
}

SportsStore/Views/Prep/Orders.cshtml
@model IEnumerable<SportsStore.Models.Order>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Orders
    </div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Customer</th>
            <th colspan="3"></th>
            <th>Total Cost</th>
        </tr>
        @foreach (var o in Model)
        {
            <tr>
                <td>@o.Id</td>
                <td>@o.Customer</td>
                <td colspan="3"></td>
                <td>@string.Format("{0:c}", o.TotalCost)</td>
            </tr>
            <tr>
                <th colspan="2"></th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
            </tr>
            foreach (var ol in o.Lines)
            {
                <tr>
                    <td colspan="2"></td>
                    <td>@ol.Product.Name</td>
                    <td>@ol.Count</td>
                    <td>@string.Format("{0:c}", ol.Product.Price)</td>
                    <td></td>
                </tr>
            }
        }
    </table>
</div>

@using (Html.BeginForm("SaveOrder", "Prep"))
{
    <input type="hidden" name="Customer" value="John Poet" />
    <input type="hidden" name="TotalCost" value="91" />
    <input type="hidden" name="lines[0].productid" value="6" />
    <input type="hidden" name="lines[0].count" value="1" />
    <input type="hidden" name="lines[1].productid" value="8" />
    <input type="hidden" name="lines[1].count" value="1" />

    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteorder/2" class="btn btn-primary">Delete</a>
}